### PR TITLE
fix for php 7.4

### PR DESCRIPTION
**Pull request by bigperson**
Fixed https://github.com/pusher/pusher-http-php/issues/247

### CODE REVIEW

**Comment by mdpye** [comment]
Hi @bigperson, thanks for the contribution.

I'm just trying to understand the context before I can review this properly.

1. What is the motivation behind the branch alias, and behind removing it?
2. Do I understand the linked error correctly? `Trying to access array offset on value of type bool` means that the `response` may sometimes be a boolean, other times an array?

Thanks

**Comment by mdpye** [comment]
Also, you may want to rebase on the most recent changes, I believe it will make the styleci checker happy (because the complaint which you appear to have inherited has been addressed recently).

**Comment by bigperson** [comment]
@mdpye 
1. branch alias did not allow using fork in my project
2. Yes, I got this error after moving from php 7.2 to 7.4

**Comment by mdpye** [comment]
Thanks. I understand the composer config might have to be edited in a fork to be usable, but I'd like to understand what the motivation for having a branch alias is in the first place, to know what we're losing before I merge its removal

**Comment by mdpye** [comment]
Hi. I've looked in to the change more thoroughly, and am convinced that the bug is a simple logic error, unrelated to PHP 7.4.

Three of the methods identified as having problems delegate to the `get(...)` method, which returns `false` if the status code is not `200`. The calling methods then attempt to check the status code themselves, but the type is now `false|array`, and if it is `array` then the status code is guaranteed to be `200`.

The `trigger*` method, and `get(...)` itself do not suffer from this, they work directly with the result of `exec_curl`, which is always an array, so they should not need to change.

I've put a fix in #251 and would welcome your review.

I'm closing this PR now, because #251 addresses the root cause.

**Pull request closed without merging**
