### PR TITLE
TODO: Added Pusher::instance() singleton method.

### PR DESCRIPTION
**Pull request by tanuck**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
I really don't like this idea.

**Comment by zimbatm** [comment]
Why not ?

**Comment by GrahamCampbell** [comment]
I don't think it makes sense for libraries to provide their own facade.

**Comment by GrahamCampbell** [comment]
People should just mange their pusher instances however they want to. For example, I bind pusher to the ioc container my framework has and then just resolve it from there.

**Comment by tanuck** [comment]
> People should just mange their pusher instances however they want to.

That is what has been accomplished. You can now manage a singleton via an IoC container, or if one is not available the library has a substitute interface for managing a singleton. Your solution is forcing the former on the user.

**Comment by GrahamCampbell** [comment]
> That is what has been accomplished. You can now manage a singleton via an IoC container

What, you can do that WITHOUT this change?

**Comment by tanuck** [comment]
True. But users without some form of singleton container now have an alternative.

**Comment by GrahamCampbell** [comment]
I don't think this belongs on the class. No other object has this.

**Comment by tanuck** [comment]
Okay. @zimbatm @leggetter what are your thoughts?

**Comment by GrahamCampbell** [comment]
I'd actually consider this to be an anti pattern.

**Comment by GrahamCampbell** [comment]
Just done a quick google search and came across this: https://github.com/domnikl/DesignPatternsPHP/tree/master/Creational/Singleton.

**Comment by GrahamCampbell** [comment]
> THIS IS CONSIDERED TO BE AN ANTI-PATTERN! FOR BETTER TESTABILITY AND MAINTAINABILITY USE DEPENDENCY INJECTION!

**Comment by leggetter** [comment]
Some libraries do it, some don't. There are pros and cons.

We are considering moving away from a singleton/global in our Ruby library and I think it's a trend we should consider elsewhere too (in fact I don't think any other libraries offer this).

My vote would be to not have `Pusher::instance` as part of the library and we enforce the use of `new Pusher(...)` with this new library.

**Comment by GrahamCampbell** [comment]
@leggetter :+1:

**Comment by GrahamCampbell** [comment]
Having a modern php library will really put pusher on the map above pubnub.

**Comment by vinkla** [comment]
:+1:

**Comment by tanuck** [comment]
@leggetter thanks for sorting that one out :+1:

**Comment by zimbatm** [comment]
Alright. Another point against is that I prefer having all the configuration happening during initialisation and then have the public properties being immutable (except internal state). It's easier to reason about mutability that way.

Closing. I'm also going to remove it from the TODO file

**Pull request closed without merging**
