### PR TITLE
v4.1.5 release

### PR DESCRIPTION
**Pull request by WillSewell**

### CODE REVIEW

**Review by elverkilde — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Should be 4.2.0 if you are following semver. If you consider this a bug fix, then the change log should not say ADDED.

**Comment by WillSewell** [comment]
@GrahamCampbell I would like to follow semver. If I understand correctly this change is not add new functionality to the public API, and therefore I don't think it is a minor release. Maybe I'm missing something.

Judging by https://github.com/semver/semver/issues/148 it seems like it's an open debate. In the past we've used patch releases when updating dependency version bounds, so I'm tempted to do the same here.

**Comment by GrahamCampbell** [comment]
In which case the change log should say FIXED. :)

**Comment by WillSewell** [comment]
Maybe technically, but I don't think the content of the CHANGELOG is strictly following semver conventions. The previous additions of PHP support use `ADDED`, so I'm going to stick to that for consistency with what is already there.

**Pull request merged**
