### PR TITLE
Add gitattributes file

### PR DESCRIPTION
**Pull request by vinkla**
Add gitattributes file for smaller download size.

### CODE REVIEW

**Comment by zimbatm** [comment]
Hi,

so this affects the github archive feature ? I'm not exactly sure of the implications of such change. Wouldn't developers be interested in having examples and the CHANGELOG.md file ?

**Comment by vinkla** [comment]
I'll fix the duplicated readme file, sorry about that. 

These files will only be ignored if the developer installs the package with `composer install --prefer-dist`. Which isn't the default behavior.

**Comment by zimbatm** [comment]
Alright, thanks for looking at details like that

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
This is actually quite common to add in your `composer.json` file for projects. This is taken from the `composer.json` file that you have when setting a new Laravel application:

```json
"config": {
    "preferred-install": "dist"
}
```

**Comment by GrahamCampbell** [comment]
Composer will use dist for tagged releases anyway, even if you don't add that config.

**Comment by vinkla** [comment]
Didn't know that, thanks for sharing!

**Pull request merged**
