### PR TITLE
Depend on the same versions of php and hhvm that we test against

### PR DESCRIPTION
**Pull request by WillSewell**
Synchonrises the versions of php and hhvm that this library is
compatible with in composer.json with the versions we are testing
against in .travis.yml.

FYI these are "[platform package](https://getcomposer.org/doc/01-basic-usage.md#platform-packages)" dependencies in the composer.json.

### CODE REVIEW

**Comment by WillSewell** [comment]
Ah yes, you do need an either/or it seems. I'll look into it.

**Comment by WillSewell** [comment]
It doesn't seem like there is an easy way of doing this: https://github.com/composer/composer/issues/2940. For now, I'll just remove the hhvm dependency.

**Comment by fitztrev** [comment]
Is there a reason PHP 7.3 is not compatible? I just tried to upgrade to v3.4.0 of this package and can't because of this constraint.

```
pusher/pusher-php-server v3.4.0 requires php >=5.4 <7.3
  -> your PHP version (7.3.3) does not satisfy that requirement.
```

**Comment by WillSewell** [comment]
Issue: https://github.com/pusher/pusher-http-php/issues/211

**Pull request merged**
