### PR TITLE
Added optional path setting

### PR DESCRIPTION
**Pull request by dtosarelli**
This PR adds optional paramater path

### CODE REVIEW

**Comment by WillSewell** [comment]
Out of curiosity, what was your motivation for doing this? Pusher Channels has a well-defined path structure in its HTTP API, and shouldn't require a prefix.

**Comment by dtosarelli** [comment]
This is useful if you use a custom installation.
In our organization we use it behind a proxy and we need a custom path.

Besides it is already implemented in pusher's javascript library:
https://github.com/pusher/pusher-js/blob/830463cb96469a941631dda95d09ff6075007f4c/README.md#wspath

**Comment by WillSewell** [comment]
Are you using standard HTTP tunneling, i.e. https://en.wikipedia.org/wiki/HTTP_tunnel? In which case I'm not sure why you would need to set a path at all? If I understand correctly would be doing a CONNECT to the proxy, and then subsequent requests would be using the standard Pusher HTTP API path scheme.

It would be helpful if you could describe your proxy setup in more detail?

**Comment by WillSewell** [comment]
We decided that `path` is the best name, for consistency with `pusher-js`. Thanks!

**Pull request merged**
