### PR TITLE
Major Refactoring and cleanup

### PR DESCRIPTION
**Pull request by Gufran**
I propose this PR as a base for next version of Pusher API.

### CODE REVIEW

**Comment by phaberest** [comment]
Pusher lacks a framework agnostic PSR-4 version, it's useless to pull it in with composer if there's no way to call it directly from its namespace.

What you did is great!

**Comment by Gufran** [comment]
Holy cow! This PR is now 2 years old and still open for discussion?

**Comment by WillSewell** [comment]
While I don't think it's realistic that we will merge this PR at this point, I am keen to have the problems that this PR is aiming to solve listed out. That way we can advocate for an investment into solving these problems (whether that's cherry-picking from this PR, or starting from scratch). Thanks!

**Comment by Gufran** [comment]
Well, hello there 2014.

**Comment by WillSewell** [comment]
This isn't going to get merged, is it?

**Pull request closed without merging**
