### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Not only is a version class pointless imo, the version in there was wrong too.

### CODE REVIEW

**Comment by zimbatm** [comment]
The reason for the separate version file is that during release it's easier to find and bump the file (or build tooling around). I'm happy to bump the version to 3.0.0

**Comment by GrahamCampbell** [comment]
I'm not sure we even need a version file anyway?

**Comment by zimbatm** [comment]
It's not strictly necessary. It's useful for us to help customers out more rapidly when they have an issue (and potentially to track adoption).

**Comment by GrahamCampbell** [comment]
Hmmm, ok.

**Comment by tanuck** [comment]
I don't think it's wise writing the version directly into the userAgent() method. Potentially move the VERSION constant into the Pusher class. A Pusher::VERSION property seems logical?

**Comment by zimbatm** [comment]
Can you expand your reasoning a bit ? I don't get the point that you want to make

**Comment by tanuck** [comment]
@zimbatm It was just a reference to some the changes included in the PR. But seen as it wasn't accepted I guess we can just forget my previous comment :)

**Comment by zimbatm** [comment]
ok :)

**Pull request closed without merging**
