### PR TITLE
Curl method reset during get call

### PR DESCRIPTION
**Pull request by simaranjit**
*Problem*
`$ch` variable is defined as static variable and kind of singleton pattern is followed to handle this. So, problem is, If two consecutive  requests are made, first is Post, second is Get, in this case system might send second request of Post type too which is fundamentally wrong. 

*How it has been fixed*
Get method should set CURLOPT_POST to 0 to avoid any kind of conflicts.

### CODE REVIEW

**Comment by simaranjit** [comment]
@zimbatm Can you please check this PR?

**Comment by zimbatm** [comment]
Can you tell me what value you get for `function_exists('curl_reset')`?

**Comment by zimbatm** [comment]
I just went ahead and implement something I wanted to do a long time ago in #106, let me know what you think of it.

**Comment by simaranjit** [comment]
@zimbatm Yes, what you implemented would fix this problem too. My concern was to fix it with minimal efforts :)

**Comment by simaranjit** [comment]
@zimbatm 

I have one input, regarding that PR, system isn't letting me comment there.
```$this->ch = null;```

IMO, we should keep that variable private and instead of initializing in constructor, it should be defined as  private variable in class variables itself. Thoughts?

**Comment by zimbatm** [comment]
Alright, thanks for the feedback. I'll close this PR and finish the other one today.

**Pull request closed without merging**
