### PR TITLE
WIP: rewrite README to follow our own conventions

### LINKED ISSUE #64: Update README to adhere to standard
The README for the 3.0.0 release should adhere to the HTTP library template:
https://github.com/pusher/pusher-http-library-template

### PR DESCRIPTION
**Pull request by zimbatm**
https://github.com/pusher/pusher-http-library-template

Fixes #64

### CODE REVIEW

**Comment by zimbatm** [comment]
@vinkla thanks. It's really really early, most of the README is going to change. I made the PR to get the github rendering.

Can I ping you back when it's ready for review ?

**Comment by vinkla** [comment]
Okay, sounds good :)

**Comment by vinkla** [comment]
Btw, is the new version targeting PHP 5.3? 5.4 was end of life in september 2015, it doesn't receive any more security fixes.

**Comment by zimbatm** [comment]
`composer.json` says 5.3.3 but I'm open to changing it. Open an issue for discussing this ? I suppose the main reason would be if something is holding us back because of 5.3-compatibility

**Comment by vinkla** [comment]
Okay, I've opened a new issue #86.

**Comment by WillSewell** [comment]
Ideally I want to focus development on the master branch, rather than this long-lived fork. Having said that, even though this branch is a WIP, it still looks like an improvement and in a mergable state. So I'm merging.

**Pull request merged**
