### PR TITLE
Support php8

### PR DESCRIPTION
**Pull request by mmachatschek**
This PR adds support for PHP 8

- PHPUnit 8 & PHPUnit 9 Support

### CODE REVIEW

**Review by devdreamsolution — APPROVED** [review]

**Comment by oyed** [comment]
Is this something that can be merged now?

**Comment by gileswells** [comment]
Thank you for the PR @mmachatschek.

I'm raising this will the engineering team to see if we can get this prioritized for review / potential merge.

**Comment by mmachatschek** [comment]
Travis PHP 8.0 config still not available

nightly flag -> https://travis-ci.org/github/pusher/pusher-http-php/builds/740788264
8.0 flag -> https://travis-ci.org/github/pusher/pusher-http-php/builds/747366791

I created #262 which would update travis to Github actions. If the PR #262 I'll update the branch there immediately to test 8.0. In case not I'll revert the commit [210e9a1](https://github.com/pusher/pusher-http-php/pull/257/commits/210e9a1ecf3824e7a9bb282d0127d2558037bad6)

**Comment by WillSewell** [comment]
This looks good! Thank you for your contribution.

**Pull request merged**
